CREATE TABLE USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PUBLIC_ID VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE (PUBLIC_ID),
  UNIQUE (USERNAME)
);

CREATE TABLE ITEMS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PUBLIC_ID VARCHAR(255) NOT NULL,
  PARENT INTEGER NULL,
  TITLE VARCHAR(255),
  DESCRIPTION TEXT,
  ARCHIVED INTEGER NOT NULL DEFAULT 0,
  COMPLETE INTEGER NOT NULL DEFAULT 0,
  OWNER INTEGER NOT NULL,
  
  PRIMARY KEY (ID),
  FOREIGN KEY (PARENT) REFERENCES ITEMS (ID),
  FOREIGN KEY (OWNER) REFERENCES USERS (ID),
  UNIQUE (PUBLIC_ID)
);
